### ISSUE TITLE
Issues on v1.3.0rc

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#2035]
- [x] [medium] Public brief view, wrong URL to the host document (pointing to the professional interface)
![ksnip_20210614-160926](https://user-images.githubusercontent.com/1557213/121906003-37909c80-cd1a-11eb-8bb0-705127fd0aa7.png)
- [x] [medium] Prof. View: in the document detail view, there is no search bar anymore
![image](https://user-images.githubusercontent.com/16501502/122001348-82f58a00-cdb0-11eb-8990-2d7fbaf57286.png)
- [x] [low] Professional interface, document detailed view, subjects not displayed (only icon). On the public interface, nothing is displayed.
- [x] [#2008] Public view: detail view of a document : you get an error in the console (it looks for an URL https://ilsdev.test.rero.ch/global/documents/None)  NOT BLOCKING
- [x] [low] Prof. view: on the main page, do a search, you get a result but the console displays "ERROR TypeError: this.suggestions$ is undefined" NOT BLOCKING
- [x] [#2061] Prof. view: document editor: there are duplicate entries ("Lié à...") in the available fields on the left 
![image](https://user-images.githubusercontent.com/16501502/121913463-b6450400-cd31-11eb-9ba2-3ed896caa784.png)
- [x] [low] Public view: some problem with languages (english/french) but no problem in the Prof. View for the same document.
![image](https://user-images.githubusercontent.com/16501502/121944580-18623100-cd53-11eb-9eb2-bc084a536544.png)
- [x] [low, improvement] On the public document detailed view when we display an empty holding serial it would be great to display something like in the pro interface "no item received". At the same time we can fix the holding header alignment.
![image](https://user-images.githubusercontent.com/127249/122000794-ae2ba980-cdaf-11eb-9890-1dc671a10094.png)
- [x] [medium] It is possible to renew loans where the new due date is equal or inferior to the previous one.
![image](https://user-images.githubusercontent.com/8154915/122003544-850d1800-cdb3-11eb-8a52-0fea9f26253d.png)
- [x] [low] After doing a checkout on a patron account, the renew button of this loan is not completely clickable.
- [x] [low] ILL requests (pro): Some space and parenthesis to delete.
![image](https://user-images.githubusercontent.com/12396034/122016888-c0aede80-cdc1-11eb-9cbe-ad16e2574b2d.png)
- [x] [#2063] The availability of a serial item should not be "on shelf" when it's not yet received (for status : late, claimed, expected, deleted).
- [x] [#2065] When trying to import from BnF, the filter by document type doesn't work if there is no subtype (ex. : serial).
![image](https://user-images.githubusercontent.com/55576980/122046629-7177a680-cddf-11eb-9430-b5a056a27420.png)

**Comment by benerken** [comment]
- [ ] [medium] Prof. View: in the document detail view, there is no search bar anymore
![image](https://user-images.githubusercontent.com/16501502/122001348-82f58a00-cdb0-11eb-8990-2d7fbaf57286.png)

**Comment by iGormilhit** [comment]
Other minor issues:
- https://github.com/rero/rero-ils/issues/2036

**Comment by iGormilhit** [comment]
Issues are either fixed or reopened in a single issue.
