### ISSUE TITLE
v1.4.0 RC bug list

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#2118]
1. [x] @iGormilhit #2119 Users cannot add an ILL request. The 'tool' menu is empty. Ex: Katie. The ILL request creation URL still exists: https://ilsdev.test.rero.ch/ill_requests/create/ Is related to https://github.com/rero/rero-ils/blob/dev/rero_ils/theme/views.py#L111
9. [x] @zannkukai #2120 #1919 is partially solved. The aim was to have the field `adminMetadata` required, not only the sub-field inside of it.
1. [x] @Garfield-fr rero/rero-ils-ui#662 Operation logs and loans history (may be related to `record.value` https://github.com/rero/rero-ils/blob/dev/rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json#L46 :
    1. [x] Operation logs do not display on the item detailed view of the professional interface. Clicking on the button result on a deactivated page and nothing else.
       ![screencast](https://user-images.githubusercontent.com/1557213/124455796-7fcf3780-dd79-11eb-8aab-612bc8e422cc.mp4)
    1. [x] Circulation history on the item detailed view of the professional interface is always empty. Furthermore, in the operation log records, I cannot discriminate loans to be anonymized from the others.
    https://github.com/rero/rero-ils/blob/dev/rero_ils/modules/operation_logs/jsonschemas/operation_logs/operation_log-v0.0.1.json#L165 doesn't have anymore the `to_anonymize` flag.
    1. [x] Professional interface: cannot load the history. Ex: https://ilsdev.test.rero.ch/professional/circulation/patron/2050124311/history The console says 'Failed to load resource: the server responded with a status of 404 (NOT FOUND)'
    1. [x] Professional interface / Circulation : do a checkout+checkin on Katie's account. It works but try to display its patron history Tab. The spinner loops and the console contains an error message "ERROR TypeError: this.loan.metadata.item_pid is undefined" (similar to point above / benerken)
4. [x] @Garfield-fr rero/rero-ils-ui#663 The translation of the circulation info from the item type not taken into account. Ex https://ilsdev.test.rero.ch/aoste/documents/299 It only displays in English.
5. [x] ~~@zannkukai Professional interface / Corporate bodies search retreives persons too. The `corporate_bodies` page title is not translated.~~
6. [x] Professional interface / Circulation : checkout/checkin box: you scan a patron barcode, it displays the patron account but the console contains errors "ERROR TypeError: r is undefined"  (not blocking / benerken)
7. [x] @zannkukai - Librarian cannot remove the e-mail of a *user*. When the e-mail field is empty, it says "This email is already taken.". Or, the librarian can save the patron personnal information without e-mail, but the e-mail is still in the patron record. This behavior is the same when a patron tries to delete her own e-mail.
    ![image](https://user-images.githubusercontent.com/8154915/124580598-93999d00-de50-11eb-9ff5-b2cc947c9241.png)

**Comment by iGormilhit** [comment]
According to

**Comment by iGormilhit** [comment]
According to

**Comment by zannkukai** [comment]
related PR : https://github.com/rero/rero-ils/pull/2120
