### ISSUE TITLE
Add data management tools

### ISSUE THREAD

**Issue by PascalRepond** [rero/rero-ils#2778]
As a developer I need a set of tools to manipulate the data for the data migration and mass corrections for all invenio instances: SONAR, rero+, UCL ils, etc.

## Brainstorming notes

1. A new module to access all projects including  reroils, sonar
2. Access to all instances of each project, for example: [bib.test.rero.ch](http://bib.test.rero.ch/), [bib.rero.ch](http://bib.rero.ch/)
3. Add/update/delete of all types of resources in database
4. Indexing of all types of resources in database
5. Different types of logging: info, errors… 
6. Access to cli commands of each instance (?)
7. Input /output to be handled here or in the personalised script
8. Indexing manipulations, DDL (Data Definition Language) of ES/Postgres
9. Migration related tasks (alembic)
10. Others

- es snap
- indexation
- update mapping
- delete index
- index in a new index
- switch
- indexing queue
- export/display/count records given a es query
- delete records, ev. with an es query
- create/update records given a JSON file
- display invenio user informations (profile, token, etc.)

- https://budibase.com/
- https://appwrite.io/

Voted module name: `rero-invenio-base`

## Tasks

* [x] Meeting/guidelines and concept + brain storming
* [x] create a new module invenio 
  * [ ] readme: with a scope
  * [ ] units testing ?, rules
* [ ] List of features to implement (tasks)
  * [ ] ...
* [ ] Install module in different projects reroils, sonar
