### ISSUE TITLE
Synchro MEF / RERO-ILS

### ISSUE THREAD

**Issue by PascalRepond** [rero/rero-ils#2849]
## User story

As a librarian, I want the updated, merged or deleted IdRef/GND entities to be automatically reported and corrected in the RERO ILS document.

## Acceptance criteria

Updated IdRef/GND records should be updated in MEF and  RERO ILS.

- [x] 1. Updated records are updated in MEF and RERO ILS: especially access points and identifier. Examples:
     - Montaigne, Michel de  ppn 027035549 (suppression de la 2e zone 200)
     - Van der Gucht, Fieke (17..-....) ppn 202360458 (date de vie mise à jour dans la vedette)
     - [x] 1.1 Changed VIAF clusters are reported in RERO ILS
     - [x] 1.2 Base identifier is indexed in the document: `"id_base": "idref:026907747"`
        - Currently all identifiers of the MEF cluster are indexed but we don't know to which one the document was linked. This will help to facilitate the updates.
- [x] 2. Merged records are updated in MEF and RERO ILS
     - old identifier and access point are updated by the new ones in RERO ILS
     - EXAMPLE / PPN 027630501 has been merged in ppn 026357313
- [x] 3. deleted or splitted records
    - Alert to system admin with list of concerned bibliographic records for each problematic authority (all the cases can be solved automatically)

## Tasks
- [x] Create specific API on the MEF server to get the last MEF version given a source id.
- [x] Create a specific API on the MEF server to know which MEF has been updated for a given period
- [x] Create a first script version on the ILS to perform the sync with detailed logs.
- [x] Inject the MEF pid in the ILS document database data.
- [x] Remove legacy sync code.
- [x] Create a tasks to perform the synchronisation.
- [x] Store the last sync date time the the errors.
- [x] Create a new entry point to monitor errors on zabbix.

## Specifications

GND spec:
https://www.dnb.de/EN/Professionell/Metadatendienste/Datenbezug/GND\_Aenderungsdienst/gndAenderungsdienst\_node.html

IdRef spec: cf. comment below

/!\\ The sync mechanism should also update RERO ILS data on the base of updated MEF record and MEF RERO RAMEAU records (when integrated into MEF). Use case: birth and death dates have been added in IdRef, then the MEF record is updated, then the RERO ILS data should be updated also.
